name = "earthapp-cloud"
main = "src/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = [ "nodejs_compat", "nodejs_zlib" ]
routes = [
    { pattern = "cloud.earth-app.com", custom_domain = true }
]
send_metrics = false

[assets]
directory = "public"
binding = "ASSETS"

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[[r2_buckets]]
binding = "R2"
bucket_name = "earth-app"
preview_bucket_name = "earth-app-preview"
