/**
 * Source-scanning half of the copy guard. `tests/copy-guards.spec.ts` walks the exported catalogs
 * from inside workerd, which cannot see copy held in a non-exported `const` - that is exactly how
 * an `addiction research` article topic hid until `topicExamples` was exported. This half reads
 * `src/` off disk and has no such blind spot, so it runs on the `node` project.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');

const BANNED: { pattern: RegExp; why: string }[] = [
	{
		pattern: /\baddict(ion|ive|ed|s)\b/i,
		why: 'behavioural addiction is a contested construct, not a DSM-5/ICD-11 diagnosis'
	},
	{
		pattern:
			/within\s+300\s*m(eters?|etres?)?\b|300\s*m(eters?|etres?)?\s+of\s+(green|a park|nature)/i,
		why: 'the 300 m green-space threshold is a planning convention with no behavioural derivation'
	},
	{
		pattern: /120\s*min(ute)?s?\s*(a|per|\/)\s*week|two hours a week (outside|outdoors|in nature)/i,
		why: 'White 2019 is cross-sectional and its authors declined to turn 120 min/week into guidance'
	},
	{
		pattern: /the amount linked to|the dose linked to/i,
		why: 'reads as a prescribed dose; there is no established one'
	},
	{
		pattern: /(reduces|cures|prevents|treats)\s+(stress|anxiety|loneliness|depression)/i,
		why: 'no causal claim is available; more contact does not even reduce loneliness (Masi 2011)'
	},
	{
		pattern: /(scientifically|clinically)\s+proven|proven\s+to\s+(reduce|improve|boost)/i,
		why: 'nothing in this evidence base is at proof strength'
	},
	{
		pattern: /verif(y|ies|ied)\s+(you|your|that you)\s+(were|are|went)/i,
		why: 'nature minutes are self-reported time outside, never verified presence'
	}
];

function sourceFiles(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...sourceFiles(full));
		// worker-configuration.d.ts is generated by wrangler; its model ids are not copy
		else if (extname(entry.name) === '.ts' && entry.name !== 'worker-configuration.d.ts') {
			out.push(full);
		}
	}
	return out;
}

// a rejected figure has to be nameable in a comment explaining the rejection, so comments do not
// count as copy
function stripComments(text: string): string {
	return text.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
}

describe('authored copy guards, scanned from source', () => {
	it('finds the source tree', () => {
		expect(sourceFiles(SRC).length).toBeGreaterThan(20);
	});

	for (const { pattern, why } of BANNED) {
		it(`never says ${pattern.source.slice(0, 42)} (${why})`, () => {
			const offenders: string[] = [];

			for (const file of sourceFiles(SRC)) {
				const text = stripComments(readFileSync(file, 'utf-8'));
				const match = text.match(pattern);
				if (match) offenders.push(`${relative(ROOT, file)}: ${match[0]}`);
			}

			expect(offenders).toEqual([]);
		});
	}

	it('strips comments before matching, so a rejection note may name the figure', () => {
		const stripped = stripComments('// 120 minutes a week is not a target\nconst a = 1;');
		expect(stripped).not.toMatch(/120\s*min(ute)?s?\s*a\s*week/i);
		expect(stripped).toContain('const a = 1;');
	});

	it('still catches the claim outside a comment', () => {
		expect(stripComments(`const copy = 'aim for 120 minutes a week';`)).toMatch(
			/120\s*min(ute)?s?\s*a\s*week/i
		);
	});

	it('does not treat a url as a comment', () => {
		expect(stripComments('const u = "https://earth-app.com";')).toContain('earth-app.com');
	});

	// the blind spot this file exists to close: a non-exported const is invisible to the
	// catalog-walking guard but not to this one
	it('sees copy in a non-exported const', () => {
		const sample = stripComments("const topics = ['addiction research'];");
		expect(sample).toMatch(BANNED[0]!.pattern);
	});
});
