name: Check Test Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
          registries: |
            https://registry.npmjs.org/
            @earth-app:https://npm.pkg.github.com|$GITHUB_TOKEN
      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tests with coverage
        run: bun run test:coverage
      - name: Archive Test Coverage
        if: success() || failure()
        uses: actions/upload-artifact@v6
        with:
          name: test-coverage
          path: coverage/
          retention-days: 30
      - name: Code Coverage Summary Report
        uses: saschanowak/CloverCodeCoverageSummary@1.1.1
        with:
          filename: coverage/clover.xml
      - name: Add Coverage to Job Summary
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-summary.md
